#!/usr/bin/env bash

[[ -z "$1" ]] && { echo -e "Error: Input .mp4 file as argument   Try: $0 <vide_file>.mp4"; exit 1; }

original_video="$1"
watermarked_video="$2"

[[ -f "$original_video" ]] || { echo "Video not found $original_video"; exit 0; }
[[ -f "$watermarked_video" ]] && { echo "Watermarked video alreay exists in local: $watermarked_video"; exit 0; }
[[ -d "$(dirname "$watermarked_video")" ]] || mkdir -p $(dirname "$watermarked_video")

# echo -e "\nAdding Bottom banner to main video ........"
# time ffmpeg -y -loglevel error -stats -i $original_video  \
# 			-i '/home/drive/watermark/bottom_video.png' \
# 			-filter_complex vstack intro.mp4
# sleep 5

ddname="$(dirname "$original_video")"
btext="$(basename "$ddname" | sed 's/_/ /g')"
# echo "-------------------> $1"
# echo "-------------------> $original_video"
# echo "-------------------> $btext"
btext="$(echo "$btext" | tr '[:lower:]' '[:upper:]')"

source_size="$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 $original_video)"
source_length="$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 -sexagesimal $original_video | cut -d . -f1)"
source_resolv="$(echo "$source_size" | sed 's/x/:/g')"
source_width="$(echo "$source_size" | awk -F 'x' '{print $1}')"
source_height="$(echo "$source_size" | awk -F 'x' '{print $2}')"

[[ $source_width -gt 1290 ]] && text_pad=150 || text_pad=20

echo "VIDEO_RESOLUTION: $source_size"
echo "VIDEO_DURATION: $source_length"
source_memory="$(du -h $original_video | awk '{print $1}')"

ffmpeg -y -loglevel error -i /home/drive/watermark/intro_source.mp4 -vf scale="${source_resolv}:force_original_aspect_ratio=increase,crop=${source_resolv}" /home/drive/watermark/intro.mp4

# ffmpeg -y -loglevel error -i $original_video -i '/home/drive/watermark/itd_big.png' \
# 	   -i '/home/drive/watermark/bottom_video.png' \
# 	   -i '/home/drive/watermark/intro.mp4' \
# 	   -filter_complex "[1]format=rgba,colorchannelmixer=aa=0.06[logo]; \
# 	   					[logo][0]scale2ref=w=oh*mdar:h=ih*0.29[logo][video]; \
# 	   					[video][logo]overlay=(W-w)/2:(H-h)/2[new]; \
# 	   					[new]drawtext=fontfile=/Users/harshajain/Library/Fonts/Poppins-Black.ttf:text=${btext}:fontcolor=black@0.2:fontsize=24::x=w-tw-${text_pad}:y=h-th-80[newa]; \
# 	   					[newa]drawtext=fontfile=/Users/harshajain/Library/Fonts/Poppins-Black.ttf:text='+91 9740672537, +91 9535440402':fontcolor=black@0.2:fontsize=18::x=w-tw-${text_pad}:y=h-th-110[newb]; \
# 	   					[2]scale=${source_width}:50:force_original_aspect_ratio=increase[2nd]; \
# 	   					[2nd][newb]vstack=inputs=2[mark]; \
# 	   					[mark]scale='min(${source_width},iw)':min'(${source_height},ih)'[out]; \
# 	   					[3:0][3:1][out]concat=n=2:v=1:a=1[outv][outa]" -map "[outv]" -map "[outa]" -vsync vfr $watermarked_video && echo "OUTPUT: $watermarked_video" || { rm -f $watermarked_video; echo "Failed to watermark video: $watermarked_video"; exit 0; }

ffmpeg -y -loglevel error \
-i "$original_video" \
-i '/home/drive/watermark/itd_big.png' \
-i '/home/drive/watermark/bottom_video.png' \
-i '/home/drive/watermark/intro.mp4' \
-filter_complex "
  [1]format=rgba,colorchannelmixer=aa=0.06[logo];
  [logo][0]scale2ref=w=oh*mdar:h=ih*0.29[logo][video];
  [video][logo]overlay=(W-w)/2:(H-h)/2[new];
  [new]drawtext=fontfile=/Users/harshajain/Library/Fonts/Poppins-Black.ttf:text='${btext}':fontcolor=black@0.2:fontsize=24:x=w-tw-${text_pad}:y=h-th-80[newa];
  [newa]drawtext=fontfile=/Users/harshajain/Library/Fonts/Poppins-Black.ttf:text='+91 9740672537, +91 9535440402':fontcolor=black@0.2:fontsize=18:x=w-tw-${text_pad}:y=h-th-110[newb];
  [2]scale=${source_width}:50:force_original_aspect_ratio=increase[bottom];
  [bottom][newb]vstack=inputs=2[mark];
  [mark]scale='min(${source_width},iw)':min'(${source_height},ih)'[out];
  [3:0][3:1][out]concat=n=2:v=1:a=1[outv][outa]
" \
-map "[outv]" -map "[outa]" \
-c:v libx264 -profile:v high -level:v 4.0 -pix_fmt yuv420p \
-c:a aac -b:a 128k -movflags +faststart -vsync vfr "$watermarked_video" && \
echo "OUTPUT: $watermarked_video" || { rm -f "$watermarked_video"; echo "Failed to watermark video: $watermarked_video"; exit 0; }

echo "VIDEO_SIZE BEFORE: $source_memory AFTER: $(du -h $watermarked_video | awk '{print $1}')"
# sleep 5

# echo -e "\nResizing main video to add intro ........"
# ffmpeg -y -loglevel error -stats -i watermark1.mp4 -vf scale=1280:720 -preset slow -crf 18 watermark.mp4
# sleep 4

# echo -e "\nAdding Intro video to main video ........"
# time ffmpeg -y -loglevel error -i '/home/drive/watermark/intro.mp4' -i watermark.mp4 -filter_complex "[0:v][0:a][1:v][1:a]concat=n=2:v=1:a=1" -vsync vfr $watermarked_video
# sleep 5


# [[ -f "intro.mp4" ]] && rm -f intro.mp4;
# [[ -f "watermark.mp4" ]] && rm -f watermark.mp4;
# [[ -f "watermark1.mp4" ]] && rm -f watermark1.mp4